apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: quay.io/keycloak/keycloak:19.0.3
        args: ["start"]
        env:
        - name: KEYCLOAK_ADMIN
          value: {{ .Values.auth.username }}
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: {{ .Values.auth.password }}
        - name: KC_PROXY
          value: "edge"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_USERNAME
          value: {{ .Values.database.username }}
        - name: KC_DB_PASSWORD
          value: {{ .Values.database.password }}
        - name: KC_DB_URL_HOST
          value: {{ .Values.database.host }}
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_URL
          value: {{ .Values.ingress.host }}
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 60
          httpGet:
            path: /realms/master
            port: 8080
